# Generated by Django 4.1.7 on 2023-04-09 09:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0003_alter_review_parent_alter_review_specialist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="specialist",
            new_name="reviewed_user",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="parent",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "reviewed_user")},
        ),
    ]
