# Generated by Django 4.1.7 on 2023-04-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("reviews", "0004_rename_specialist_review_reviewed_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reviewed_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_specialist",
                to="accounts.specialist",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_parent",
                to="accounts.parent",
            ),
        ),
    ]
