# Generated by Django 4.1.7 on 2023-04-25 07:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_gamelog_level_alter_gamelog_unique_together"),
        ("token_economy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="game",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="tokeneconomy",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinLengthValidator(0)]
            ),
        ),
    ]
