# Generated by Django 4.1.7 on 2023-04-29 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_child_parent"),
        ("token_economy", "0003_alter_tokeneconomy_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokeneconomy",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="economy_user",
                to="accounts.child",
            ),
        ),
    ]
