# Generated by Django 4.1.7 on 2023-04-29 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_alter_gamelog_player"),
        ("token_economy", "0005_alter_tokeneconomy_quantity_alter_tokeneconomy_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="game",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="games.game",
            ),
        ),
    ]
