# Generated by Django 4.2.2 on 2023-06-07 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_economy', '0006_alter_token_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokeneconomy',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
