# Generated by Django 4.1.7 on 2023-04-30 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_alter_child_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Aprroved"),
                            ("PENDING", "Pending"),
                            ("DECLINED", "Declined"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_parent",
                        to="accounts.parent",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_specialist",
                        to="accounts.specialist",
                    ),
                ),
            ],
            options={
                "unique_together": {("parent", "specialist", "date_time")},
            },
        ),
    ]
