# Generated by Django 4.1.7 on 2023-04-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_child_parent"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_parent",
                to="accounts.parent",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="specialist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_specialist",
                to="accounts.specialist",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("specialist", "date_time"), ("parent", "date_time")},
        ),
    ]
