# Generated by Django 4.1.7 on 2023-04-25 07:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelog",
            name="level",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamelog",
            unique_together={("player", "game")},
        ),
    ]
