# Generated by Django 4.1.7 on 2023-04-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_child_parent"),
        ("games", "0002_alter_gamelog_level_alter_gamelog_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelog",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player",
                to="accounts.child",
            ),
        ),
    ]
